-- MySQL Script generated by MySQL Workbench
-- Wed Sep  3 01:29:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tiendavirtual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendavirtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendavirtual` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tiendavirtual` ;

-- -----------------------------------------------------
-- Table `tiendavirtual`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendavirtual`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `fechaRegistro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendavirtual`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,0) NOT NULL,
  `estado` ENUM('Pendiente', 'Pagado', 'Enviado', 'Entregado', 'Cancelado') NULL DEFAULT 'Pendiente',
  `metodoPago` ENUM('Tarjeta', 'Efectivo', 'Transferencia') NULL DEFAULT 'Efectivo',
  `direccionEntrega` VARCHAR(150) NULL DEFAULT NULL,
  `idCliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idCliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `tiendavirtual`.`cliente` (`idCliente`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendavirtual`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `reputacion` DECIMAL(3,2) NULL DEFAULT '0.00',
  `fechaRegistro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVendedor`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendavirtual`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NULL DEFAULT '1',
  `estado` ENUM('Usado', 'Reacondicionado', 'Nuevo') NULL DEFAULT 'Usado',
  `fechaPublicacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idVendedor` INT NULL DEFAULT NULL,
  `idCategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `idVendedor` (`idVendedor` ASC) VISIBLE,
  INDEX `idCategoria` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `tiendavirtual`.`vendedor` (`idVendedor`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `producto_ibfk_2`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `tiendavirtual`.`categoria` (`idCategoria`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 501
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendavirtual`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`detallepedido` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NULL DEFAULT NULL,
  `idProducto` INT NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `precioUnitario` DECIMAL(10,0) NOT NULL,
  `nombreProducto` VARCHAR(100) NULL DEFAULT NULL,
  `idVendedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `idPedido` (`idPedido` ASC) VISIBLE,
  INDEX `idProducto` (`idProducto` ASC) VISIBLE,
  INDEX `idVendedor` (`idVendedor` ASC) VISIBLE,
  CONSTRAINT `detallepedido_ibfk_1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `tiendavirtual`.`pedido` (`idPedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detallepedido_ibfk_2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tiendavirtual`.`producto` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detallepedido_ibfk_3`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `tiendavirtual`.`vendedor` (`idVendedor`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 181
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendavirtual`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendavirtual`.`devolucion` (
  `idDevolucion` INT NOT NULL AUTO_INCREMENT,
  `idDetalle` INT NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `monto` DECIMAL(10,0) NOT NULL,
  `fechaDevolucion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('Pendiente', 'Aprobada', 'Rechazada', 'Reembolsada') NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`idDevolucion`),
  INDEX `idDetalle` (`idDetalle` ASC) VISIBLE,
  CONSTRAINT `devolucion_ibfk_1`
    FOREIGN KEY (`idDetalle`)
    REFERENCES `tiendavirtual`.`detallepedido` (`idDetalle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
